version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - ./data:/srv
      - ./00-websockets.conf:/etc/nginx/conf.d/default.conf
      - ./TSL:/etc/nginx/TSL #сертификаты
    networks:
      - my_host


  server:
    ports:
      - 8080:8080
    build: .
    networks:
      - my_host

networks:
  my_host:
    driver: host


