version: '3'

services:
  nginx:
    image: nginx
    #restart: always
    ports:
      - 443:443
    volumes:
      - ./data:/srv
      - ./00-websockets.conf:/etc/nginx/conf.d/default.conf
      - ./TSL:/etc/nginx/TSL #сертификаты
    networks:
      - default


  server:
    ports:
      - 8080:8080
    build: .
    networks:
      - default
    depends_on:
      - db


  db:
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=toor
    container_name: db
    image: mongodb/mongodb-community-server:6.0.4-ubi8
    ports:
      - 27017:27017
    volumes:
      - smln-server-data:/data/db
    command: >
      bash -c "mongod --bind_ip_all"

    networks:
      - default


volumes:
  smln-server-data:
    external: false


networks:
  default:
    driver: "bridge"


