version: '3'

services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 444:444
    volumes:
      - ./data:/srv
      - ./00-websockets.conf:/etc/nginx/conf.d/default.conf
      - ./TSL:/etc/nginx/TSL #сертификаты
    networks:
      - default


  server:
    ports:
      - 8081:8081
    build: .
    networks:
      - default
    depends_on:
      - db


  db:
    image: mongo
    container_name: db
    environment:
      - MONGO_INITDB_DATABASE=db
      # Логин и пароль для доступа к базе данных.
      # При смене логина или пароля не забудьте сменить их в init0mongo.js,
      # а также в конфигурационном файле сервера
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - smln-server-data:/data/db
      - './init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js'
      #- ./mongoConfig:/data/configdb
    ports:
      - 27017:27017
    restart: unless-stopped
    command: [ --auth ]
    networks:
      - default


volumes:
  smln-server-data:
    external: false


networks:
  default:
    driver: "bridge"


